# DBT profiles.yml for Spark connection. Ensure environment variables are set for SPARK_HOST, SPARK_PORT, SPARK_USER, SPARK_SCHEMA.
default:
  target: dev
  outputs:
    dev:
      type: spark
      method: thrift
      host: "{{ env_var('SPARK_HOST') }}"
      port: "{{ env_var('SPARK_PORT') | as_number }}"
      user: "{{ env_var('SPARK_USER') }}"
      schema: "{{ env_var('SPARK_SCHEMA') }}"
      threads: 4
      connect_timeout: 60
      retry_all: true

athena:
  target: dev
  outputs:
    dev:
      type: athena
      s3_staging_dir: s3://dbt-core-athena-test-bucket/dbt-output/
      region_name: us-east-2
      database: AwsDataCatalog
      schema: test
      data_catalog: AwsDataCatalog
      aws_access_key_id: "{{ env_var('AWS_ACCESS_KEY_ID') }}"
      aws_secret_access_key: "{{ env_var('AWS_SECRET_ACCESS_KEY') }}"
      # Or use IAM roles if running on ECS 