spark_glue_iceberg:
  target: dev
  outputs:
    dev:
      type: spark
      method: thrift
      host: "44.223.27.73"
      port: 10000
      user: "hadoop"
      schema: "default"
      threads: 4
      connect_timeout: 60
      retry_all: true
      session_properties:
        spark.sql.catalog.glue_catalog: org.apache.iceberg.spark.SparkCatalog
        spark.sql.catalog.glue_catalog.warehouse: s3://everag-dev-config/iceberg-config/
        spark.sql.catalog.glue_catalog.catalog-impl: org.apache.iceberg.aws.glue.GlueCatalog
        spark.sql.catalog.glue_catalog.io-impl: org.apache.iceberg.aws.s3.S3FileIO
        spark.sql.catalog.glue_catalog.lock-impl: org.apache.iceberg.aws.glue.DynamoLockManager
        spark.sql.catalog.glue_catalog.lock.table: myGlueLockTable 