default:
  target: dev
  outputs:
    dev:
      type: spark
      method: thrift
      host: "{{ env_var('SPARK_HOST') }}"
      port: "{{ env_var('SPARK_PORT') | as_number }}"
      user: "{{ env_var('SPARK_USER') }}"
      schema: "{{ env_var('SPARK_SCHEMA') }}"
      threads: 4
      connect_timeout: 60
      retry_all: true 